name: Build  and Release

on:
  workflow_dispatch:
  push:
    branches: [ main ]

# 🔑 این بلاک را اضافه کنید
permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.24'

      - name: Build for linux/arm (ARMv7)
        run: |
          cd cmd/mhr-cfw
          GOOS=linux GOARCH=arm GOARM=7 go build -o findns-armv7 .
          mkdir -p ${{ github.workspace }}/output
          cp build-armv7 ${{ github.workspace }}/output/

      - name: Create Release and Upload Asset
        uses: softprops/action-gh-release@v2
        with:
          tag_name: v${{ github.run_number }}
          name: Build ${{ github.run_number }}
          files: output/build-armv7
