name: Build and Release mhr-cfw-go

on:
  workflow_dispatch:  # امکان اجرای دستی از تب Actions
  push:
    branches: [ master ]

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        goos: [linux]
        goarch: [arm64, amd64, arm]
        include:
          - goarch: arm
            goarm: 7

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22'

      - name: Build
        env:
          GOOS: ${{ matrix.goos }}
          GOARCH: ${{ matrix.goarch }}
          GOARM: ${{ matrix.goarm || '0' }}
        run: |
          cd cmd/mhr-cfw
          go build -ldflags "-s -w" -o mhr-cfw-go-${{ matrix.goos }}-${{ matrix.goarch }}${{ matrix.goarm && format('v{0}', matrix.goarm) }} .

      - name: Upload to Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: v${{ github.run_number }}
          name: Build ${{ github.run_number }}
          files: cmd/mhr-cfw/mhr-cfw-go-*
          token: ${{ secrets.GITHUB_TOKEN }}
